### ISSUE TITLE
[FEATURE REQUEST] starkiller on Kali ARM platforms available as package

### ISSUE THREAD

**Issue by rcfa** [BC-SECURITY/Starkiller#62]
**Is your feature request related to a problem? Please describe.**
starkiller can’t be installed on KALI running on an ARM platform, at least not with the recommended ‘apt install starkiller’ command

**Describe the solution you'd like**
I’d love to see feature parity between arm64 and amd64 Kali platforms.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by vinnybod** [comment]
I'll forward this to Kali since they manage the builds

**Comment by sbrun** [comment]
Hi,

I'm the maintainer of Starkiller in Kali. Starkiller is not yet available on ARM64 because it fails to build.

I found the issue: `electron-icon-builder` requires `phantomjs-prebuilt` which is not available on ARM and I can't install `phantomjs` to workaround because it's no longer in Debian/Kali.
I can build Starkiller on ARM64 if I don't use `electron-icon-builder`, but I'm not sure of the consequences on Starkiller application.

If the consequences are limited, I can drop `electron-icon-builder` only on ARM64 build. Or maybe another module (installable on ARM) can do the same job as `electron-icon-builder`?

**Comment by vinnybod** [comment]
I think I have a solution for this which removes electron-icon-builder as a dependency of the project. I will test it out on an ARM machine myself and share the results here.

**Comment by More2Chi** [comment]
let know ; i can test on my nethunter build

**Comment by vinnybod** [comment]
@sbrun I was able to successfully build from the branch `remove-icon-builder-dependency` with the following command on an ARM64 Ubuntu VM.
I don't think Kali uses AppImage, but hopefully, other targets will work as well. If you hit another roadblock, let me know. If it is successful, we can merge this down.

```
 yarn electron:build --arm64 --linux AppImage
 ```

**Comment by sbrun** [comment]
I have imported the patch and the build is successful on ARM64. I think it can be merged.

I have uploaded 1.7.0-Kali-0kali3 in kali-dev. It will be available in few hours on all Kali mirrors.

**Comment by vinnybod** [comment]
Targetting this to be in the builds for `v1.8.0-beta.2`
